export interface RegexPattern {
  id: string;
  name: string;
  category: "Web" | "India" | "Dates & numbers" | "Text";
  pattern: string;
  flags: string;
  explanation: string;
  caveat?: string;
  matches: string[];
  rejects: string[];
}

export const PATTERNS: RegexPattern[] = [
  {
    id: "email",
    name: "Email address (practical)",
    category: "Web",
    pattern: "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$",
    flags: "",
    explanation: "Letters, digits and ._%+- before the @; a domain with at least one dot and a 2+ letter top-level domain.",
    caveat: "Covers real-world addresses, not every address the RFC technically allows. The only true test is sending a confirmation email.",
    matches: ["asha.rao@example.com", "support+tools@expensico.in", "a_b@sub.domain.co.uk"],
    rejects: ["asha@", "@example.com", "asha@example", "asha rao@example.com"],
  },
  {
    id: "url",
    name: "Web URL (http/https)",
    category: "Web",
    pattern: "^https?:\\/\\/(?:[A-Za-z0-9-]+\\.)+[A-Za-z]{2,}(?::\\d{2,5})?(?:[/?#][^\\s]*)?$",
    flags: "",
    explanation: "http:// or https://, a domain name with a top-level domain, optional port, then any path/query/fragment without spaces.",
    caveat: "Doesn't accept IP addresses or localhost. For full validation use the URL constructor in code.",
    matches: ["https://expensico.com", "http://www.example.co.in:8080/a/b?x=1#top"],
    rejects: ["ftp://example.com", "https://example", "https://exa mple.com"],
  },
  {
    id: "ipv4",
    name: "IPv4 address",
    category: "Web",
    pattern: "^(?:(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)\\.){3}(?:25[0-5]|2[0-4]\\d|1\\d\\d|[1-9]?\\d)$",
    flags: "",
    explanation: "Four numbers from 0 to 255 separated by dots, without leading zeros.",
    matches: ["192.168.1.1", "0.0.0.0", "255.255.255.255"],
    rejects: ["256.1.1.1", "192.168.1", "01.2.3.4"],
  },
  {
    id: "hex-color",
    name: "Hex colour",
    category: "Web",
    pattern: "^#(?:[0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$",
    flags: "",
    explanation: "# followed by 3, 4, 6 or 8 hex digits (with optional alpha).",
    matches: ["#fff", "#0d7a63", "#0d7a6380"],
    rejects: ["0d7a63", "#12345", "#ggg"],
  },
  {
    id: "slug",
    name: "URL slug",
    category: "Web",
    pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
    flags: "",
    explanation: "Lowercase words of letters and digits joined by single hyphens.",
    matches: ["pdf-to-jpg", "emi-calculator", "tools"],
    rejects: ["PDF-to-jpg", "pdf--jpg", "-pdf", "pdf_to_jpg"],
  },
  {
    id: "uuid",
    name: "UUID",
    category: "Web",
    pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$",
    flags: "i",
    explanation: "8-4-4-4-12 hex digits with a valid version (1–8) and RFC variant.",
    matches: ["550e8400-e29b-41d4-a716-446655440000", "0192D4F8-3B6A-7C41-9D2E-5F8A1B3C4D5E"],
    rejects: ["550e8400e29b41d4a716446655440000", "550e8400-e29b-91d4-a716-446655440000"],
  },
  {
    id: "in-mobile",
    name: "Indian mobile number",
    category: "India",
    pattern: "^(?:\\+91[\\s-]?|0)?[6-9]\\d{9}$",
    flags: "",
    explanation: "Optional +91 or leading 0, then 10 digits starting with 6, 7, 8 or 9.",
    matches: ["9876543210", "+91 9876543210", "+91-6123456789", "09876543210"],
    rejects: ["5876543210", "98765 43210", "+919876543"],
  },
  {
    id: "pin",
    name: "Indian PIN code",
    category: "India",
    pattern: "^[1-9]\\d{5}$",
    flags: "",
    explanation: "Six digits; the first digit (postal zone) is never 0.",
    matches: ["110001", "560034"],
    rejects: ["011001", "11001", "1100011"],
  },
  {
    id: "pan",
    name: "PAN",
    category: "India",
    pattern: "^[A-Z]{5}\\d{4}[A-Z]$",
    flags: "",
    explanation: "Five capital letters, four digits, one capital letter (e.g. ABCDE1234F).",
    caveat: "Checks the format only. The 4th letter indicates the holder type (P = individual, C = company…).",
    matches: ["ABCDE1234F", "AAAPZ1234C"],
    rejects: ["abcde1234f", "ABCD1234F", "ABCDE12345"],
  },
  {
    id: "gstin",
    name: "GSTIN",
    category: "India",
    pattern: "^\\d{2}[A-Z]{5}\\d{4}[A-Z][1-9A-Z]Z[0-9A-Z]$",
    flags: "",
    explanation: "2-digit state code, the holder's PAN, an entity number, the letter Z and a check character — 15 characters in total.",
    caveat: "Doesn't verify the checksum character or the state code; confirm on the GST portal.",
    matches: ["27AAPFU0939F1ZV", "29ABCDE1234F1Z5"],
    rejects: ["27AAPFU0939F1V", "2AAAPFU0939F1ZV", "27aapfu0939f1zv"],
  },
  {
    id: "ifsc",
    name: "IFSC code",
    category: "India",
    pattern: "^[A-Z]{4}0[A-Z0-9]{6}$",
    flags: "",
    explanation: "Four-letter bank code, a zero, then a six-character branch code.",
    matches: ["SBIN0001234", "HDFC0ABC123"],
    rejects: ["SBIN1001234", "SBI0001234", "sbin0001234"],
  },
  {
    id: "aadhaar",
    name: "Aadhaar number (format)",
    category: "India",
    pattern: "^[2-9]\\d{3}\\s?\\d{4}\\s?\\d{4}$",
    flags: "",
    explanation: "12 digits, optionally grouped 4-4-4 with spaces; never starts with 0 or 1.",
    caveat: "Format only — Aadhaar also has a Verhoeff check digit. Never store Aadhaar numbers unless legally required.",
    matches: ["2345 6789 0123", "234567890123"],
    rejects: ["1234 5678 9012", "2345-6789-0123", "23456789012"],
  },
  {
    id: "vehicle",
    name: "Indian vehicle registration",
    category: "India",
    pattern: "^[A-Z]{2}[ -]?\\d{1,2}[ -]?[A-Z]{0,3}[ -]?\\d{4}$",
    flags: "",
    explanation: "State code, district number, optional series letters and a 4-digit number (e.g. MH 12 AB 1234).",
    caveat: "Doesn't cover BH-series or older special formats.",
    matches: ["MH12AB1234", "KA 05 MN 4321", "DL-3C-1234"],
    rejects: ["M12AB1234", "MH12AB123"],
  },
  {
    id: "inr-amount",
    name: "Amount with Indian grouping",
    category: "India",
    pattern: "^₹?\\s?(?:\\d{1,3}|\\d{1,2}(?:,\\d{2})*,\\d{3})(?:\\.\\d{1,2})?$",
    flags: "",
    explanation: "Optional ₹, digits grouped in lakhs and crores (1,00,000 or 12,34,567.50), up to 2 decimals.",
    matches: ["₹1,00,000", "12,34,567.50", "999", "1,000"],
    rejects: ["10,00", "1,000,000", "1,00,0000"],
  },
  {
    id: "date-iso",
    name: "Date (YYYY-MM-DD)",
    category: "Dates & numbers",
    pattern: "^\\d{4}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12]\\d|3[01])$",
    flags: "",
    explanation: "ISO 8601 date with valid month (01–12) and day (01–31) ranges.",
    caveat: "Accepts impossible dates like 2026-02-31; check them with a date library.",
    matches: ["2026-10-03", "1999-12-31"],
    rejects: ["2026-13-01", "26-10-03", "2026-1-3"],
  },
  {
    id: "date-dmy",
    name: "Date (DD/MM/YYYY)",
    category: "Dates & numbers",
    pattern: "^(?:0[1-9]|[12]\\d|3[01])\\/(?:0[1-9]|1[0-2])\\/\\d{4}$",
    flags: "",
    explanation: "Day, month and four-digit year separated by slashes, as commonly written in India.",
    matches: ["03/10/2026", "31/12/1999"],
    rejects: ["3/10/2026", "32/01/2026", "03-10-2026"],
  },
  {
    id: "time-24",
    name: "Time (24-hour)",
    category: "Dates & numbers",
    pattern: "^(?:[01]\\d|2[0-3]):[0-5]\\d(?::[0-5]\\d)?$",
    flags: "",
    explanation: "HH:MM with optional :SS, hours 00–23.",
    matches: ["09:30", "23:59:59", "00:00"],
    rejects: ["24:00", "9:30", "12:60"],
  },
  {
    id: "decimal",
    name: "Decimal number",
    category: "Dates & numbers",
    pattern: "^-?\\d+(?:\\.\\d+)?$",
    flags: "",
    explanation: "Optional minus sign, digits, and an optional decimal part.",
    matches: ["42", "-3.14", "0.5"],
    rejects: [".5", "1.", "1e5", "1,000"],
  },
  {
    id: "password",
    name: "Strong password rule",
    category: "Text",
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{12,}$",
    flags: "",
    explanation: "At least 12 characters with a lowercase letter, an uppercase letter, a digit and a symbol (lookaheads).",
    caveat: "Length matters more than character rules. Consider allowing long passphrases instead.",
    matches: ["Tr0ub4dor&Horse", "Expensico#2026!"],
    rejects: ["password123", "Sh0rt!", "ALLUPPERCASE1!"],
  },
  {
    id: "username",
    name: "Username",
    category: "Text",
    pattern: "^[A-Za-z][A-Za-z0-9_]{2,15}$",
    flags: "",
    explanation: "3–16 characters: starts with a letter, then letters, digits or underscores.",
    matches: ["asha_rao", "dev42"],
    rejects: ["4sha", "ab", "asha.rao"],
  },
  {
    id: "extra-spaces",
    name: "Repeated whitespace",
    category: "Text",
    pattern: "[ \\t]{2,}",
    flags: "g",
    explanation: "Two or more spaces or tabs in a row — replace with a single space to tidy text.",
    matches: ["too  many", "tab\t\there"],
    rejects: ["just one space"],
  },
];
