/**
 * Tool registry — metadata only (no React, no browser APIs).
 *
 * Imported by routes, the sitemap, next.config redirects, the search index and tests. next.config
 * loads this file and its imports outside the bundler, where `@/` aliases don't resolve: use
 * relative imports here and in lib/convert/catalog.ts and config/site.ts.
 * UI lives in registry/components.ts (client) and content in registry/content.ts (server).
 */

import { CONVERSIONS, isConversionAvailable, type ConversionDef } from "../lib/convert/catalog";
import { getCategory, type CategoryId } from "./categories";

/**
 * How a tool handles data. Drives the privacy badge on every tool page, so it must be accurate.
 * - local-file: reads files you choose, processes them in the browser, never uploads
 * - local: no files; everything you type is processed in the browser
 * - server: files are uploaded to the processing service and deleted after processing
 * - hybrid: browser by default, with an optional, clearly-labelled server mode
 */
export type ProcessingMode = "local-file" | "local" | "server" | "hybrid";

export interface ToolMeta {
  slug: string;
  category: CategoryId;
  /** H1 and card title. */
  title: string;
  /** <title> override when the H1 alone is too short or ambiguous. */
  metaTitle?: string;
  /** Meta description and on-page summary. 120–160 characters, unique. */
  description: string;
  keywords: string[];
  icon: string;
  processing: ProcessingMode;
  related: string[];
  alsoIn?: CategoryId[];
  /** Extra legacy/alternative paths that should 301 to this tool. */
  aliases?: string[];
  popular?: boolean;
  addedAt: string;
  kind: "tool" | "converter";
  /** Set for kind === "converter". */
  conversionSlug?: string;
}

const T = (meta: Omit<ToolMeta, "kind">): ToolMeta => ({ ...meta, kind: "tool" });

const LAUNCH = "2026-10-03";

const STATIC_TOOLS: ToolMeta[] = [
  // ───────────── File tools: viewers ─────────────
  T({
    slug: "pdf-viewer",
    category: "files",
    alsoIn: ["pdf"],
    title: "PDF Viewer",
    metaTitle: "Online PDF Viewer — Open and Read PDF Files Privately",
    description: "Open and read PDF files in your browser with zoom, page navigation, search and thumbnails. Nothing is uploaded; the PDF stays on your device.",
    keywords: ["pdf viewer", "open pdf", "read pdf online", "view pdf", "pdf reader"],
    icon: "file-text",
    processing: "local-file",
    related: ["pdf-to-jpg", "pdf-merge", "pdf-metadata", "pdf-to-text"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "csv-viewer",
    category: "files",
    title: "CSV Viewer",
    metaTitle: "CSV Viewer — Open, Search, Sort and Filter CSV Files Online",
    description: "Open large CSV files as a fast, searchable table. Sort, filter, resize columns and export the result. Handles quotes and Unicode; runs locally.",
    keywords: ["csv viewer", "open csv", "csv reader", "view csv online", "csv table"],
    icon: "table",
    processing: "local-file",
    related: ["csv-to-xlsx", "csv-to-json", "excel-viewer", "json-to-csv"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "json-viewer",
    category: "files",
    alsoIn: ["developer"],
    title: "JSON Viewer",
    metaTitle: "JSON Viewer — Collapsible Tree View for JSON Files",
    description: "Explore JSON as a collapsible tree with search, path copying and type highlights. Open a file or paste data; everything stays in your browser.",
    keywords: ["json viewer", "json tree", "view json", "json explorer", "open json file"],
    icon: "braces",
    processing: "local-file",
    related: ["json-formatter", "json-validator", "json-to-csv", "xml-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "xml-viewer",
    category: "files",
    title: "XML Viewer",
    description: "View XML files as a collapsible tree with attributes and text, or as formatted source. Validation errors point to the exact line. Private and local.",
    keywords: ["xml viewer", "open xml file", "xml tree view", "view xml online"],
    icon: "code-xml",
    processing: "local-file",
    related: ["xml-formatter", "xml-to-json", "json-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "markdown-viewer",
    category: "files",
    title: "Markdown Viewer",
    description: "Open .md files and read them rendered, with tables, task lists and code blocks — or switch to source. Rendered safely in your browser.",
    keywords: ["markdown viewer", "md viewer", "open md file", "readme viewer"],
    icon: "file-type",
    processing: "local-file",
    related: ["markdown-editor", "markdown-to-html", "text-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "text-viewer",
    category: "files",
    title: "Text File Viewer",
    metaTitle: "TXT Viewer — Open Text and Log Files Online",
    description: "Open TXT, LOG and other plain-text files with line numbers, search, word wrap and encoding detection. Large files stay fast and private.",
    keywords: ["txt viewer", "text file viewer", "open txt file", "log file viewer"],
    icon: "file",
    processing: "local-file",
    related: ["word-counter", "text-diff", "markdown-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "html-viewer",
    category: "files",
    title: "HTML Viewer",
    description: "Preview HTML files safely in a sandbox with scripts disabled, and view the formatted source side by side. Nothing is uploaded.",
    keywords: ["html viewer", "preview html", "open html file", "html renderer"],
    icon: "globe",
    processing: "local-file",
    related: ["html-formatter", "html-to-text", "markdown-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "excel-viewer",
    category: "files",
    title: "Excel Viewer",
    metaTitle: "Excel Viewer — Open XLSX, XLS and ODS Files Online",
    description: "Open Excel XLSX, XLS and ODS spreadsheets without Excel. Switch between sheets, search cells and export to CSV — all in your browser.",
    keywords: ["excel viewer", "xlsx viewer", "open xlsx", "xls viewer", "view spreadsheet online"],
    icon: "sheet",
    processing: "local-file",
    related: ["xlsx-to-csv", "xlsx-to-json", "csv-viewer"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "docx-viewer",
    category: "files",
    title: "Word Document Viewer",
    metaTitle: "DOCX Viewer — Open Word Documents Online",
    description: "Read Word DOCX documents in your browser with headings, lists, tables and images. No Word installation and no upload required.",
    keywords: ["docx viewer", "word viewer", "open docx", "view word document online"],
    icon: "file-text",
    processing: "local-file",
    related: ["docx-to-html", "docx-to-text", "word-counter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "image-viewer",
    category: "files",
    title: "Image Viewer",
    description: "View JPG, PNG, WebP, GIF, AVIF, BMP and SVG images with zoom, rotation, dimensions and file details. Images stay on your device.",
    keywords: ["image viewer", "photo viewer", "open webp", "view image online"],
    icon: "image",
    processing: "local-file",
    related: ["image-metadata", "image-compressor", "image-resizer"],
    addedAt: LAUNCH,
  }),

  // ───────────── File tools: images ─────────────
  T({
    slug: "image-compressor",
    category: "files",
    title: "Image Compressor",
    metaTitle: "Image Compressor — Reduce JPG, PNG and WebP File Size",
    description: "Compress JPG, PNG and WebP images in bulk with a quality slider, optional resize and a before/after size comparison. Runs entirely in your browser.",
    keywords: ["image compressor", "compress image", "reduce image size", "compress jpg", "compress png", "image size reducer", "photo compressor"],
    icon: "minimize-2",
    processing: "local-file",
    related: ["image-resizer", "png-to-webp", "jpg-to-pdf", "pdf-compress"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "image-resizer",
    category: "files",
    title: "Image Resizer",
    metaTitle: "Image Resizer — Resize Photos by Pixels or Percentage",
    description: "Resize images to exact pixel dimensions or a percentage, with aspect-ratio lock and high-quality resampling. Batch resize privately in your browser.",
    keywords: ["image resizer", "resize image", "resize photo", "change image dimensions", "resize jpg"],
    icon: "scaling",
    processing: "local-file",
    related: ["image-compressor", "image-cropper", "jpg-to-png"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "image-cropper",
    category: "files",
    title: "Image Cropper",
    description: "Crop images with a draggable frame or exact pixel values, using presets like square, 16:9 and passport size. Fast, free and private.",
    keywords: ["image cropper", "crop image", "crop photo", "crop to square", "passport photo crop"],
    icon: "crop",
    processing: "local-file",
    related: ["image-resizer", "image-compressor", "image-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "image-metadata",
    category: "files",
    title: "Image Metadata (EXIF) Viewer",
    description: "See the EXIF data hidden in photos — camera, lens, date taken and GPS location — and remove it before sharing. Processed on your device.",
    keywords: ["exif viewer", "image metadata", "photo metadata", "remove exif", "gps from photo"],
    icon: "info",
    processing: "local-file",
    related: ["image-viewer", "image-compressor", "file-info"],
    addedAt: LAUNCH,
  }),

  // ───────────── File tools: utilities ─────────────
  T({
    slug: "file-info",
    category: "files",
    title: "File Information Viewer",
    description: "Find out what a file really is: detected type from its contents, size, extension mismatch warnings and SHA-256 checksum. Nothing is uploaded.",
    keywords: ["file info", "file type checker", "what file is this", "file signature", "check file type"],
    icon: "file-search",
    processing: "local-file",
    related: ["hash-generator", "file-size-converter", "image-metadata"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "file-size-converter",
    category: "files",
    title: "File Size Converter",
    description: "Convert between bytes, KB, MB, GB and TB in both decimal (1000) and binary (1024) units, and see why your 1 TB drive shows 931 GB.",
    keywords: ["file size converter", "mb to gb", "kb to mb", "bytes converter", "mib vs mb"],
    icon: "hard-drive",
    processing: "local",
    related: ["file-info", "image-compressor", "pdf-compress"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "zip-creator",
    category: "files",
    title: "ZIP File Creator",
    description: "Bundle multiple files into a single ZIP archive in your browser, with optional compression. Your files never leave your device.",
    keywords: ["create zip", "zip files online", "compress files to zip", "make zip file"],
    icon: "file-archive",
    processing: "local-file",
    related: ["zip-extractor", "image-compressor", "pdf-merge"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "zip-extractor",
    category: "files",
    title: "ZIP Extractor",
    metaTitle: "ZIP Extractor — Open and Unzip Files Online",
    description: "Open ZIP archives in your browser, preview the file list with sizes, and download individual files or everything. Protected against zip bombs.",
    keywords: ["unzip online", "zip extractor", "open zip file", "extract zip"],
    icon: "package-open",
    processing: "local-file",
    related: ["zip-creator", "file-info"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "file-compare",
    category: "files",
    title: "File Compare",
    description: "Check whether two files are identical using SHA-256 checksums, and see a line-by-line diff for text files. Works locally with any file type.",
    keywords: ["compare files", "file diff", "are two files the same", "checksum compare"],
    icon: "git-compare",
    processing: "local-file",
    related: ["text-diff", "hash-generator", "file-info"],
    addedAt: LAUNCH,
  }),

  // ───────────── PDF tools ─────────────
  T({
    slug: "pdf-merge",
    category: "pdf",
    title: "Merge PDF",
    metaTitle: "Merge PDF — Combine PDF Files in Your Browser",
    description: "Combine several PDFs into one file in the order you choose. Merging happens in your browser, so confidential documents are never uploaded.",
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger"],
    icon: "combine",
    processing: "local-file",
    related: ["pdf-split", "pdf-compress", "jpg-to-pdf", "pdf-extract-pages"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "pdf-split",
    category: "pdf",
    title: "Split PDF",
    description: "Split a PDF into separate files by page ranges, every N pages or one file per page. Fast, private splitting with no upload.",
    keywords: ["split pdf", "separate pdf pages", "pdf splitter", "divide pdf"],
    icon: "split",
    processing: "local-file",
    related: ["pdf-extract-pages", "pdf-merge", "pdf-delete-pages"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "pdf-compress",
    category: "pdf",
    title: "Compress PDF",
    metaTitle: "Compress PDF — Reduce PDF File Size",
    description: "Make PDFs smaller for email and upload limits. Choose lossless optimisation or stronger image-based compression, with sizes shown before you download.",
    keywords: ["compress pdf", "reduce pdf size", "pdf compressor", "shrink pdf", "make pdf smaller"],
    icon: "minimize-2",
    processing: "hybrid",
    related: ["pdf-merge", "image-compressor", "pdf-split"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "pdf-rotate",
    category: "pdf",
    title: "Rotate PDF",
    description: "Rotate all pages or selected pages of a PDF by 90°, 180° or 270° and save the result permanently. Preview thumbnails, no upload.",
    keywords: ["rotate pdf", "turn pdf pages", "fix sideways pdf", "rotate pdf page"],
    icon: "rotate-cw",
    processing: "local-file",
    related: ["pdf-merge", "pdf-delete-pages", "pdf-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "pdf-extract-pages",
    category: "pdf",
    title: "Extract PDF Pages",
    description: "Pick pages from a PDF by clicking thumbnails or typing ranges, and save them as a new PDF. The original file is not changed or uploaded.",
    keywords: ["extract pdf pages", "save pdf pages", "select pages from pdf", "pdf page extractor"],
    icon: "file-output",
    processing: "local-file",
    related: ["pdf-split", "pdf-delete-pages", "pdf-merge"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "pdf-delete-pages",
    category: "pdf",
    title: "Delete PDF Pages",
    description: "Remove unwanted pages from a PDF — blank pages, cover sheets, duplicates — and download the cleaned-up file. Processed locally.",
    keywords: ["delete pdf pages", "remove pages from pdf", "pdf page remover"],
    icon: "file-minus",
    processing: "local-file",
    related: ["pdf-extract-pages", "pdf-rotate", "pdf-merge"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "pdf-metadata",
    category: "pdf",
    title: "PDF Metadata Viewer",
    description: "See a PDF's title, author, creator app, dates, PDF version and page sizes, and remove identifying metadata before sharing it.",
    keywords: ["pdf metadata", "pdf properties", "pdf author", "remove pdf metadata", "pdf info"],
    icon: "info",
    processing: "local-file",
    related: ["pdf-viewer", "file-info", "image-metadata"],
    addedAt: LAUNCH,
  }),

  // ───────────── Finance ─────────────
  T({
    slug: "emi-calculator",
    category: "finance",
    title: "EMI Calculator",
    metaTitle: "EMI Calculator — Home, Car and Personal Loan EMI with Schedule",
    description: "Calculate your monthly loan EMI, total interest and full amortization schedule for home, car or personal loans. Includes the formula and a worked example.",
    keywords: ["emi calculator", "loan emi", "home loan emi", "car loan emi", "personal loan emi", "emi formula"],
    icon: "landmark",
    processing: "local",
    related: ["loan-calculator", "debt-payoff-calculator", "simple-interest-calculator", "sip-calculator"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "sip-calculator",
    category: "finance",
    title: "SIP Calculator",
    metaTitle: "SIP Calculator — Mutual Fund SIP Returns with Step-up",
    description: "Estimate the future value of a monthly SIP with optional annual step-up. See invested amount, estimated gains and a year-by-year growth table.",
    keywords: ["sip calculator", "mutual fund sip", "step up sip", "sip returns", "systematic investment plan"],
    icon: "trending-up",
    processing: "local",
    related: ["compound-interest-calculator", "fd-calculator", "inflation-calculator", "savings-goal-calculator"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "fd-calculator",
    category: "finance",
    title: "FD Calculator",
    metaTitle: "FD Calculator — Fixed Deposit Maturity and Interest",
    description: "Calculate fixed deposit maturity value and interest with monthly, quarterly, half-yearly or yearly compounding, plus payout options.",
    keywords: ["fd calculator", "fixed deposit calculator", "fd maturity", "fd interest"],
    icon: "piggy-bank",
    processing: "local",
    related: ["rd-calculator", "compound-interest-calculator", "sip-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "rd-calculator",
    category: "finance",
    title: "RD Calculator",
    metaTitle: "RD Calculator — Recurring Deposit Maturity Value",
    description: "Find the maturity amount of a recurring deposit using the quarterly-compounding method Indian banks use, with a month-by-month schedule.",
    keywords: ["rd calculator", "recurring deposit calculator", "rd maturity", "post office rd"],
    icon: "calendar-clock",
    processing: "local",
    related: ["fd-calculator", "sip-calculator", "savings-goal-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "simple-interest-calculator",
    category: "finance",
    title: "Simple Interest Calculator",
    description: "Calculate simple interest, total amount, rate, principal or time — whichever you need — with the SI formula explained step by step.",
    keywords: ["simple interest calculator", "si calculator", "simple interest formula"],
    icon: "percent",
    processing: "local",
    related: ["compound-interest-calculator", "emi-calculator", "fd-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "compound-interest-calculator",
    category: "finance",
    title: "Compound Interest Calculator",
    description: "See how money grows with compound interest and regular contributions, at any compounding frequency, with a yearly breakdown table.",
    keywords: ["compound interest calculator", "ci calculator", "compounding calculator", "compound interest formula"],
    icon: "trending-up",
    processing: "local",
    related: ["simple-interest-calculator", "sip-calculator", "fd-calculator", "inflation-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "loan-calculator",
    category: "finance",
    title: "Loan Calculator",
    metaTitle: "Loan Calculator — Affordability, Tenure and Prepayment",
    description: "Work out how much you can borrow for a given EMI, how long a loan will take to repay, and how much a prepayment saves in interest.",
    keywords: ["loan calculator", "loan eligibility", "loan tenure calculator", "prepayment calculator", "how much loan can i get"],
    icon: "landmark",
    processing: "local",
    related: ["emi-calculator", "debt-payoff-calculator", "salary-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "salary-calculator",
    category: "finance",
    title: "Salary Calculator (CTC to In-hand)",
    metaTitle: "Salary Calculator — CTC to In-hand Salary (India)",
    description: "Estimate monthly take-home pay from your CTC under India's new or old tax regime, including EPF, professional tax and income tax.",
    keywords: ["salary calculator", "ctc to in hand", "take home salary", "in hand salary calculator", "income tax calculator india"],
    icon: "wallet",
    processing: "local",
    related: ["pf-calculator", "budget-calculator", "percentage-calculator"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "pf-calculator",
    category: "finance",
    title: "PF Calculator",
    metaTitle: "PF Calculator — EPF Balance at Retirement",
    description: "Project your EPF balance at retirement from basic salary, contribution rates, salary growth and the EPF interest rate, with the EPS split explained.",
    keywords: ["pf calculator", "epf calculator", "provident fund calculator", "epf interest", "pf balance"],
    icon: "shield-check",
    processing: "local",
    related: ["salary-calculator", "sip-calculator", "compound-interest-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "gst-calculator",
    category: "finance",
    title: "GST Calculator",
    description: "Add GST to a price or extract GST from an inclusive amount, with the CGST/SGST or IGST split shown for any rate.",
    keywords: ["gst calculator", "gst inclusive", "gst exclusive", "cgst sgst", "reverse gst"],
    icon: "receipt",
    processing: "local",
    related: ["percentage-calculator", "discount-calculator", "budget-calculator"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "percentage-calculator",
    category: "finance",
    alsoIn: ["productivity"],
    title: "Percentage Calculator",
    description: "Solve every everyday percentage question: X% of Y, what percent X is of Y, percentage change, and increase or decrease by a percentage.",
    keywords: ["percentage calculator", "percent of", "percentage change", "percentage increase", "percentage decrease"],
    icon: "percent",
    processing: "local",
    related: ["discount-calculator", "gst-calculator", "inflation-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "discount-calculator",
    category: "finance",
    title: "Discount Calculator",
    description: "Find the sale price and savings for any discount, including stacked discounts like 50% + 20%, and the effective overall discount.",
    keywords: ["discount calculator", "sale price calculator", "percent off", "double discount"],
    icon: "tag",
    processing: "local",
    related: ["percentage-calculator", "gst-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "inflation-calculator",
    category: "finance",
    title: "Inflation Calculator",
    description: "See how inflation erodes money over time: the future cost of today's expenses, and what a future amount is worth in today's money.",
    keywords: ["inflation calculator", "future value inflation", "purchasing power", "real value of money"],
    icon: "trending-down",
    processing: "local",
    related: ["savings-goal-calculator", "sip-calculator", "compound-interest-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "savings-goal-calculator",
    category: "finance",
    title: "Savings Goal Calculator",
    description: "Find the monthly saving needed to reach a goal by a target date, accounting for expected returns, inflation and money already saved.",
    keywords: ["savings goal calculator", "how much to save monthly", "goal planner", "target savings"],
    icon: "target",
    processing: "local",
    related: ["sip-calculator", "inflation-calculator", "budget-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "budget-calculator",
    category: "finance",
    title: "Budget Calculator",
    metaTitle: "Budget Calculator — Monthly Budget Planner with 50/30/20",
    description: "Plan a monthly budget: list income and expenses by category, see what's left, and compare your split with the 50/30/20 guideline.",
    keywords: ["budget calculator", "monthly budget planner", "50 30 20 rule", "expense planner"],
    icon: "pie-chart",
    processing: "local",
    related: ["expense-splitter", "savings-goal-calculator", "salary-calculator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "expense-splitter",
    category: "finance",
    title: "Expense Splitter",
    metaTitle: "Expense Splitter — Split Bills and Settle Up with Friends",
    description: "Split shared trip or flat expenses fairly, then see the fewest payments needed to settle up. Saved in your browser, no sign-up.",
    keywords: ["expense splitter", "split bills", "split expenses with friends", "who owes whom", "trip expense calculator"],
    icon: "users",
    processing: "local",
    related: ["budget-calculator", "percentage-calculator"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "debt-payoff-calculator",
    category: "finance",
    title: "Debt Payoff Calculator",
    description: "Compare avalanche and snowball strategies to pay off multiple loans and credit cards, and see your debt-free date and total interest.",
    keywords: ["debt payoff calculator", "avalanche vs snowball", "credit card payoff", "debt free date"],
    icon: "flag",
    processing: "local",
    related: ["emi-calculator", "loan-calculator", "budget-calculator"],
    addedAt: LAUNCH,
  }),

  // ───────────── Productivity ─────────────
  T({
    slug: "notepad",
    category: "productivity",
    title: "Online Notepad",
    description: "A distraction-free notepad that auto-saves in your browser. Pick up where you left off, see word counts and download as a text file.",
    keywords: ["online notepad", "notepad", "text editor online", "scratchpad", "autosave notes"],
    icon: "notebook-pen",
    processing: "local",
    related: ["word-counter", "markdown-editor", "todo-list"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "markdown-editor",
    category: "productivity",
    title: "Markdown Editor",
    description: "Write Markdown with a live, side-by-side preview, formatting shortcuts and export to .md or HTML. Your draft auto-saves in this browser.",
    keywords: ["markdown editor", "md editor", "markdown preview", "online markdown"],
    icon: "file-pen",
    processing: "local",
    related: ["markdown-viewer", "markdown-to-html", "notepad"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "word-counter",
    category: "productivity",
    title: "Word Counter",
    description: "Count words, characters, sentences and paragraphs as you type, with reading time, speaking time and top keywords. Text stays in your browser.",
    keywords: ["word counter", "word count", "count words", "essay word count", "reading time"],
    icon: "type",
    processing: "local",
    related: ["character-counter", "sentence-counter", "case-converter"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "character-counter",
    category: "productivity",
    title: "Character Counter",
    description: "Count characters with and without spaces and check limits for X/Twitter, SMS, meta descriptions and more, with emoji counted correctly.",
    keywords: ["character counter", "character count", "letter counter", "sms character count", "tweet length"],
    icon: "baseline",
    processing: "local",
    related: ["word-counter", "sentence-counter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "sentence-counter",
    category: "productivity",
    title: "Sentence Counter",
    description: "Count sentences, see average sentence length, spot overly long sentences and get a Flesch readability score for English text.",
    keywords: ["sentence counter", "count sentences", "readability score", "long sentence checker"],
    icon: "pilcrow",
    processing: "local",
    related: ["word-counter", "character-counter", "text-formatter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "case-converter",
    category: "productivity",
    title: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case and more in one click.",
    keywords: ["case converter", "uppercase to lowercase", "title case", "camelcase converter", "snake case"],
    icon: "case-sensitive",
    processing: "local",
    related: ["text-formatter", "word-counter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "text-formatter",
    category: "productivity",
    title: "Text Formatter & Cleaner",
    description: "Clean up messy text: trim spaces, remove line breaks or blank lines, de-duplicate and sort lines, and strip formatting from pasted content.",
    keywords: ["text formatter", "remove line breaks", "remove extra spaces", "sort lines", "remove duplicate lines"],
    icon: "wand-sparkles",
    processing: "local",
    related: ["case-converter", "text-diff", "word-counter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "text-diff",
    category: "productivity",
    alsoIn: ["developer"],
    title: "Text Diff Checker",
    description: "Compare two texts and highlight added, removed and changed lines and words, side by side or inline. Private comparison in your browser.",
    keywords: ["text diff", "compare text", "diff checker", "find differences between two texts"],
    icon: "git-compare",
    processing: "local",
    related: ["file-compare", "text-formatter", "json-formatter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "lorem-ipsum-generator",
    category: "productivity",
    title: "Lorem Ipsum Generator",
    description: "Generate placeholder text for designs and mock-ups by paragraphs, sentences or words, optionally starting with the classic “Lorem ipsum”.",
    keywords: ["lorem ipsum", "placeholder text", "dummy text generator"],
    icon: "text",
    processing: "local",
    related: ["word-counter", "markdown-editor"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "qr-code-generator",
    category: "productivity",
    title: "QR Code Generator",
    description: "Create QR codes for links, text, Wi-Fi, UPI payments, email and phone. Pick colours and size, then download PNG or SVG. No tracking, no expiry.",
    keywords: ["qr code generator", "create qr code", "wifi qr code", "upi qr code", "qr code maker"],
    icon: "qr-code",
    processing: "local",
    related: ["password-generator", "url-encoder-decoder", "uuid-generator"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "password-generator",
    category: "productivity",
    alsoIn: ["developer"],
    title: "Password Generator",
    description: "Generate strong random passwords with your browser's cryptographic random generator. Choose length and character types and see the strength.",
    keywords: ["password generator", "strong password", "random password", "secure password"],
    icon: "key-round",
    processing: "local",
    related: ["hash-generator", "uuid-generator", "qr-code-generator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "date-calculator",
    category: "productivity",
    title: "Date Calculator",
    description: "Count days between two dates (including or excluding weekends), add or subtract days, weeks or months, and calculate exact age.",
    keywords: ["date calculator", "days between dates", "age calculator", "add days to date", "working days calculator"],
    icon: "calendar",
    processing: "local",
    related: ["countdown-timer", "timestamp-converter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "countdown-timer",
    category: "productivity",
    title: "Countdown Timer",
    description: "Count down to a time or run a simple timer with optional sound, Pomodoro presets and a full-screen view. Works offline once loaded.",
    keywords: ["countdown timer", "online timer", "pomodoro timer", "countdown to date"],
    icon: "timer",
    processing: "local",
    related: ["date-calculator", "todo-list"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "todo-list",
    category: "productivity",
    title: "To-do List",
    description: "A simple, fast to-do list with priorities, due dates and filters. Saved in your browser automatically — no account needed.",
    keywords: ["to do list", "todo list online", "task list", "simple todo app"],
    icon: "list-todo",
    processing: "local",
    related: ["checklist", "notepad", "countdown-timer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "checklist",
    category: "productivity",
    title: "Checklist Maker",
    description: "Create reusable checklists for packing, moving, travel or routines. Tick items off, reset for next time, and print or copy the list.",
    keywords: ["checklist maker", "checklist", "packing list", "printable checklist"],
    icon: "list-checks",
    processing: "local",
    related: ["todo-list", "notepad"],
    addedAt: LAUNCH,
  }),

  // ───────────── Developer ─────────────
  T({
    slug: "json-formatter",
    category: "developer",
    aliases: ["/tools/json-formatter"],
    title: "JSON Formatter",
    metaTitle: "JSON Formatter & Beautifier — Pretty Print JSON Online",
    description: "Format, beautify and minify JSON with configurable indentation, key sorting and precise error locations. Safe for tokens — nothing leaves your browser.",
    keywords: ["json formatter", "json beautifier", "pretty print json", "format json online"],
    icon: "braces",
    processing: "local",
    related: ["json-validator", "json-viewer", "json-minifier", "json-to-csv"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "json-validator",
    category: "developer",
    title: "JSON Validator",
    description: "Validate JSON and get the exact line, column and a plain-English explanation of any syntax error, including trailing commas and single quotes.",
    keywords: ["json validator", "validate json", "json lint", "json syntax checker"],
    icon: "badge-check",
    processing: "local",
    related: ["json-formatter", "yaml-validator", "json-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "json-minifier",
    category: "developer",
    title: "JSON Minifier",
    description: "Minify JSON by removing all unnecessary whitespace, and see exactly how many bytes you saved. Validates as it minifies.",
    keywords: ["json minifier", "minify json", "compress json", "json compact"],
    icon: "minimize-2",
    processing: "local",
    related: ["json-formatter", "json-validator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "base64-encoder-decoder",
    category: "developer",
    title: "Base64 Encoder / Decoder",
    description: "Encode and decode Base64 and Base64URL for text (full UTF-8) and files, including data URLs and image previews. Runs locally.",
    keywords: ["base64 encode", "base64 decode", "base64 converter", "image to base64", "base64url"],
    icon: "binary",
    processing: "local-file",
    related: ["url-encoder-decoder", "jwt-decoder", "hash-generator"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "url-encoder-decoder",
    category: "developer",
    title: "URL Encoder / Decoder",
    description: "Percent-encode or decode URLs and query parameters, and break a URL into its parts with an editable query-string table.",
    keywords: ["url encode", "url decode", "percent encoding", "query string parser"],
    icon: "link",
    processing: "local",
    related: ["base64-encoder-decoder", "jwt-decoder"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "jwt-decoder",
    category: "developer",
    title: "JWT Decoder",
    description: "Decode JSON Web Tokens to inspect the header, payload and expiry, and optionally verify HS256 signatures. Tokens never leave your browser.",
    keywords: ["jwt decoder", "decode jwt", "jwt parser", "json web token"],
    icon: "key-square",
    processing: "local",
    related: ["base64-encoder-decoder", "json-formatter", "timestamp-converter"],
    popular: true,
    addedAt: LAUNCH,
  }),
  T({
    slug: "uuid-generator",
    category: "developer",
    alsoIn: ["productivity"],
    title: "UUID Generator",
    description: "Generate cryptographically random UUID v4 or time-ordered UUID v7 identifiers in bulk, and validate or inspect existing UUIDs.",
    keywords: ["uuid generator", "guid generator", "uuid v4", "uuid v7", "random uuid"],
    icon: "fingerprint",
    processing: "local",
    related: ["password-generator", "hash-generator", "timestamp-converter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "regex-tester",
    category: "developer",
    title: "Regex Tester",
    description: "Test JavaScript regular expressions with live match highlighting, capture groups, flags and replace preview. Protected against runaway patterns.",
    keywords: ["regex tester", "regular expression tester", "regex online", "test regex javascript"],
    icon: "regex",
    processing: "local",
    related: ["regex-generator", "text-diff", "json-formatter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "regex-generator",
    category: "developer",
    title: "Regex Pattern Library",
    metaTitle: "Regex Generator — Common Patterns Explained",
    description: "Ready-made, tested regular expressions for emails, URLs, phone numbers, PIN codes, PAN, GSTIN, dates and more, with explanations.",
    keywords: ["regex generator", "common regex patterns", "email regex", "pan card regex", "gstin regex"],
    icon: "library",
    processing: "local",
    related: ["regex-tester", "url-encoder-decoder"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "timestamp-converter",
    category: "developer",
    alsoIn: ["productivity"],
    aliases: ["/developer/unix-timestamp-converter"],
    title: "Unix Timestamp Converter",
    description: "Convert Unix timestamps (seconds or milliseconds) to human dates in any time zone and back. Includes ISO 8601 and relative time.",
    keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp"],
    icon: "clock",
    processing: "local",
    related: ["date-calculator", "cron-expression-generator", "jwt-decoder"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "cron-expression-generator",
    category: "developer",
    title: "Cron Expression Generator",
    description: "Build cron schedules visually, translate any cron expression into plain English and preview the next run times in your time zone.",
    keywords: ["cron generator", "cron expression", "crontab", "cron schedule", "cron explained"],
    icon: "calendar-clock",
    processing: "local",
    related: ["timestamp-converter", "regex-tester"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "sql-formatter",
    category: "developer",
    title: "SQL Formatter",
    description: "Beautify SQL queries for PostgreSQL, MySQL, SQL Server, SQLite, BigQuery and more, with keyword case and indentation options.",
    keywords: ["sql formatter", "sql beautifier", "format sql online", "pretty print sql"],
    icon: "database",
    processing: "local",
    related: ["json-formatter", "javascript-formatter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "html-formatter",
    category: "developer",
    title: "HTML Formatter",
    description: "Beautify HTML with consistent indentation using Prettier. Untangle messy markup from CMS exports, emails and minified pages, all in your browser.",
    keywords: ["html formatter", "html beautifier", "format html", "pretty print html"],
    icon: "code-xml",
    processing: "local",
    related: ["css-formatter", "javascript-formatter", "html-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "css-formatter",
    category: "developer",
    title: "CSS Formatter",
    description: "Format or minify CSS, SCSS and Less with Prettier. Untangle minified stylesheets or shrink them for production.",
    keywords: ["css formatter", "css beautifier", "css minifier", "format scss"],
    icon: "paintbrush",
    processing: "local",
    related: ["html-formatter", "javascript-formatter", "color-converter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "javascript-formatter",
    category: "developer",
    title: "JavaScript Formatter",
    description: "Format JavaScript and TypeScript with Prettier: choose quotes, semicolons and line width. Beautify minified scripts to read them.",
    keywords: ["javascript formatter", "js beautifier", "typescript formatter", "prettier online"],
    icon: "file-code",
    processing: "local",
    related: ["json-formatter", "css-formatter", "html-formatter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "yaml-validator",
    category: "developer",
    title: "YAML Validator",
    description: "Validate YAML and see errors with line numbers, then view the parsed result as JSON. Ideal for Kubernetes, Docker Compose and CI files.",
    keywords: ["yaml validator", "yaml lint", "validate yaml", "yml checker"],
    icon: "badge-check",
    processing: "local",
    related: ["yaml-to-json", "json-validator", "json-to-yaml"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "xml-formatter",
    category: "developer",
    title: "XML Formatter",
    description: "Pretty-print or minify XML with validation and precise error locations. Handles namespaces, CDATA and comments, entirely in your browser.",
    keywords: ["xml formatter", "xml beautifier", "pretty print xml", "xml minify"],
    icon: "code-xml",
    processing: "local",
    related: ["xml-viewer", "xml-to-json", "json-formatter"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "hash-generator",
    category: "developer",
    title: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-384 and SHA-512 hashes of text or files, and verify downloads against a published checksum.",
    keywords: ["hash generator", "sha256 generator", "md5 generator", "file checksum", "verify checksum"],
    icon: "hash",
    processing: "local-file",
    related: ["file-compare", "password-generator", "base64-encoder-decoder"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "color-converter",
    category: "developer",
    title: "Color Converter",
    description: "Convert colours between HEX, RGB, HSL, HSV, CMYK and OKLCH, pick from a colour wheel and check WCAG contrast against text.",
    keywords: ["color converter", "hex to rgb", "rgb to hex", "hsl converter", "contrast checker"],
    icon: "palette",
    processing: "local",
    related: ["css-formatter", "image-viewer"],
    addedAt: LAUNCH,
  }),
  T({
    slug: "http-status-codes",
    category: "developer",
    title: "HTTP Status Codes",
    metaTitle: "HTTP Status Codes — Complete Reference with Explanations",
    description: "A searchable reference of HTTP status codes from 100 to 511, with what each means, when servers send it and how to handle it.",
    keywords: ["http status codes", "http 404", "http 500", "status code list", "http response codes"],
    icon: "server",
    processing: "local",
    related: ["url-encoder-decoder", "jwt-decoder"],
    addedAt: LAUNCH,
  }),
];

function converterToTool(def: ConversionDef): ToolMeta {
  return {
    slug: def.slug,
    category: "convert",
    alsoIn: def.alsoIn,
    title: def.title,
    description: def.description,
    keywords: def.keywords,
    icon: "repeat",
    processing: def.engine === "server" ? "server" : "local-file",
    related: def.related ?? [],
    popular: def.popular,
    addedAt: def.addedAt,
    kind: "converter",
    conversionSlug: def.slug,
  };
}

const CONVERTER_TOOLS: ToolMeta[] = CONVERSIONS.filter((c) => c.landing && isConversionAvailable(c)).map(converterToTool);

export const TOOLS: ToolMeta[] = [...STATIC_TOOLS, ...CONVERTER_TOOLS];

const bySlug = new Map(TOOLS.map((t) => [t.slug, t]));

export function getTool(slug: string): ToolMeta | undefined {
  return bySlug.get(slug);
}

export function toolPath(tool: Pick<ToolMeta, "category" | "slug">): string {
  return `/${getCategory(tool.category).path}/${tool.slug}`;
}

export function toolsInCategory(category: CategoryId): ToolMeta[] {
  return TOOLS.filter((t) => t.category === category || t.alsoIn?.includes(category));
}

/** Related tools, resolving slugs and silently skipping any that aren't currently available. */
export function relatedTools(tool: ToolMeta, limit = 6): ToolMeta[] {
  return tool.related
    .map((slug) => bySlug.get(slug))
    .filter((t): t is ToolMeta => Boolean(t))
    .slice(0, limit);
}

export function popularTools(): ToolMeta[] {
  return TOOLS.filter((t) => t.popular);
}

/** 301 redirects for alternative category paths and aliases → canonical URL. */
export function toolRedirects(): { source: string; destination: string }[] {
  const out: { source: string; destination: string }[] = [];
  for (const tool of TOOLS) {
    const destination = toolPath(tool);
    for (const cat of tool.alsoIn ?? []) {
      out.push({ source: `/${getCategory(cat).path}/${tool.slug}`, destination });
    }
    for (const alias of tool.aliases ?? []) out.push({ source: alias, destination });
  }
  return out.filter((r) => r.source !== r.destination);
}
