// Writes the Fluent Emoji icons Expensico uses (Microsoft, MIT, via @iconify-json/fluent-emoji)
// to public/icons/*.svg and a small TypeScript map. Icons load as cached images, so menus and
// cards never carry the 3,000-icon set (or even these SVGs) in a JavaScript bundle.
// Usage: pnpm icons
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const { getIconData, iconToSVG, iconToHTML, replaceIDs } = require("@iconify/utils");
const here = dirname(fileURLToPath(import.meta.url));
const set = require("@iconify-json/fluent-emoji/icons.json");
const map = JSON.parse(readFileSync(join(here, "icon-map.json"), "utf8"));
delete map.$comment;

const outDir = join(here, "../public/icons");
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

const missing = [];
const written = new Set();
for (const value of Object.values(map).flatMap((v) => v.split("+"))) {
  const [kind, name] = value.split(":");
  if (kind === "doc") continue;
  if (kind !== "emoji") {
    missing.push(value);
    continue;
  }
  if (written.has(name)) continue;
  const data = getIconData(set, name);
  if (!data) {
    missing.push(value);
    continue;
  }
  const svg = iconToSVG(data);
  const html = iconToHTML(replaceIDs(svg.body, name), { ...svg.attributes, width: "64", height: "64" });
  writeFileSync(join(outDir, `${name}.svg`), html);
  written.add(name);
}
if (missing.length) {
  console.error(`Unknown icons: ${missing.join(", ")}`);
  process.exit(1);
}

writeFileSync(
  join(outDir, "LICENSE.txt"),
  "Icons in this folder are Microsoft Fluent Emoji (https://github.com/microsoft/fluentui-emoji).\nCopyright (c) Microsoft Corporation. Licensed under the MIT License.\n",
);

const out = `// Generated by scripts/generate-icons.mjs. Do not edit; change scripts/icon-map.json and run \`pnpm icons\`.
// "emoji:<name>" icons are Microsoft Fluent Emoji (MIT), served from /icons/<name>.svg.

/** Tool slug or special key → "emoji:<name>" | "doc:<format>", optionally "+<badge>". */
export const ICON_MAP: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;
writeFileSync(join(here, "../src/components/tool/icons.generated.ts"), out);
console.log(`Wrote ${written.size} SVG files for ${Object.keys(map).length} keys.`);
