export interface StatusCode {
  code: number;
  name: string;
  summary: string;
  detail?: string;
  /** Spec or "non-standard". */
  source: string;
}

export const STATUS_CODES: StatusCode[] = [
  { code: 100, name: "Continue", summary: "The server received the request headers; the client should send the body.", detail: "Used with the Expect: 100-continue header so large uploads aren't sent to a server that will reject them.", source: "RFC 9110" },
  { code: 101, name: "Switching Protocols", summary: "The server is switching to the protocol the client requested via the Upgrade header.", detail: "Most commonly seen when a connection is upgraded to WebSocket.", source: "RFC 9110" },
  { code: 103, name: "Early Hints", summary: "Preliminary headers sent before the final response so the browser can start preloading resources.", source: "RFC 8297" },
  { code: 200, name: "OK", summary: "The request succeeded.", detail: "The meaning depends on the method: GET returns the resource, POST returns the result of the action.", source: "RFC 9110" },
  { code: 201, name: "Created", summary: "The request succeeded and a new resource was created.", detail: "Should include a Location header pointing to the new resource. Typical response to a successful POST.", source: "RFC 9110" },
  { code: 202, name: "Accepted", summary: "The request was accepted for processing, but processing isn't finished.", detail: "Used for asynchronous jobs; the response often includes a URL to check status.", source: "RFC 9110" },
  { code: 203, name: "Non-Authoritative Information", summary: "The response was modified by a transforming proxy.", source: "RFC 9110" },
  { code: 204, name: "No Content", summary: "The request succeeded and there is no body to return.", detail: "Common for DELETE and for PUT/PATCH when the client doesn't need the updated resource.", source: "RFC 9110" },
  { code: 205, name: "Reset Content", summary: "The client should reset the document view, for example clear a form.", source: "RFC 9110" },
  { code: 206, name: "Partial Content", summary: "The server is returning only part of the resource, as requested with a Range header.", detail: "Used for resumable downloads and video streaming.", source: "RFC 9110" },
  { code: 207, name: "Multi-Status", summary: "Multiple status codes for multiple operations (WebDAV).", source: "RFC 4918" },
  { code: 300, name: "Multiple Choices", summary: "There are several possible responses; the client should choose one.", source: "RFC 9110" },
  { code: 301, name: "Moved Permanently", summary: "The resource has a new permanent URL, given in the Location header.", detail: "Search engines transfer ranking to the new URL. Browsers may change POST to GET when following it — use 308 to keep the method.", source: "RFC 9110" },
  { code: 302, name: "Found", summary: "The resource is temporarily at another URL.", detail: "Browsers usually change POST to GET when following it. Use 307 to preserve the method.", source: "RFC 9110" },
  { code: 303, name: "See Other", summary: "Get the result from another URL using GET.", detail: "The standard response after a form POST (Post/Redirect/Get pattern).", source: "RFC 9110" },
  { code: 304, name: "Not Modified", summary: "The cached copy is still valid; no body is sent.", detail: "Returned for conditional requests using If-None-Match (ETag) or If-Modified-Since.", source: "RFC 9110" },
  { code: 307, name: "Temporary Redirect", summary: "Temporarily redirect, keeping the same method and body.", source: "RFC 9110" },
  { code: 308, name: "Permanent Redirect", summary: "Permanently redirect, keeping the same method and body.", source: "RFC 9110" },
  { code: 400, name: "Bad Request", summary: "The server can't process the request because it's malformed.", detail: "Invalid JSON, missing required fields or invalid parameters. The response body should explain what's wrong.", source: "RFC 9110" },
  { code: 401, name: "Unauthorized", summary: "Authentication is required or has failed.", detail: "Despite the name, it means unauthenticated. The client should log in or send valid credentials. Includes a WWW-Authenticate header.", source: "RFC 9110" },
  { code: 402, name: "Payment Required", summary: "Reserved for future use; some APIs use it for billing problems.", source: "RFC 9110" },
  { code: 403, name: "Forbidden", summary: "The server understood the request but refuses to authorise it.", detail: "The client is known but lacks permission. Logging in again won't help.", source: "RFC 9110" },
  { code: 404, name: "Not Found", summary: "The server can't find the requested resource.", detail: "Also used to hide the existence of a resource from unauthorised users.", source: "RFC 9110" },
  { code: 405, name: "Method Not Allowed", summary: "The method isn't supported for this resource, e.g. DELETE on a read-only endpoint.", detail: "Must include an Allow header listing supported methods.", source: "RFC 9110" },
  { code: 406, name: "Not Acceptable", summary: "The server can't produce a response matching the Accept headers.", source: "RFC 9110" },
  { code: 407, name: "Proxy Authentication Required", summary: "The client must authenticate with a proxy.", source: "RFC 9110" },
  { code: 408, name: "Request Timeout", summary: "The server timed out waiting for the request.", source: "RFC 9110" },
  { code: 409, name: "Conflict", summary: "The request conflicts with the current state of the resource.", detail: "Examples: editing a stale version, or creating a user whose email already exists.", source: "RFC 9110" },
  { code: 410, name: "Gone", summary: "The resource was deliberately removed and won't come back.", detail: "Tells search engines to drop the URL faster than a 404.", source: "RFC 9110" },
  { code: 411, name: "Length Required", summary: "The request needs a Content-Length header.", source: "RFC 9110" },
  { code: 412, name: "Precondition Failed", summary: "A condition in the request headers (such as If-Match) wasn't met.", detail: "Used for optimistic concurrency control.", source: "RFC 9110" },
  { code: 413, name: "Content Too Large", summary: "The request body is larger than the server allows.", detail: "Formerly called “Payload Too Large”. Seen when uploading files above a limit.", source: "RFC 9110" },
  { code: 414, name: "URI Too Long", summary: "The URL is longer than the server will process.", source: "RFC 9110" },
  { code: 415, name: "Unsupported Media Type", summary: "The request body's format isn't supported.", detail: "Often a missing or wrong Content-Type header, e.g. sending form data to a JSON endpoint.", source: "RFC 9110" },
  { code: 416, name: "Range Not Satisfiable", summary: "The requested byte range is outside the resource.", source: "RFC 9110" },
  { code: 417, name: "Expectation Failed", summary: "The server can't meet the Expect request header.", source: "RFC 9110" },
  { code: 418, name: "I'm a teapot", summary: "An April Fools' joke from the Hyper Text Coffee Pot Control Protocol.", detail: "Not part of HTTP proper, but reserved so it won't be reused, and some sites use it playfully.", source: "RFC 2324 (non-standard)" },
  { code: 421, name: "Misdirected Request", summary: "The request was sent to a server that can't respond for this host.", source: "RFC 9110" },
  { code: 422, name: "Unprocessable Content", summary: "The request is well-formed but contains invalid data.", detail: "Widely used by APIs for validation errors, e.g. a malformed email address.", source: "RFC 9110" },
  { code: 423, name: "Locked", summary: "The resource is locked (WebDAV).", source: "RFC 4918" },
  { code: 425, name: "Too Early", summary: "The server won't risk processing a request that might be replayed.", source: "RFC 8470" },
  { code: 426, name: "Upgrade Required", summary: "The client must switch to a different protocol.", source: "RFC 9110" },
  { code: 428, name: "Precondition Required", summary: "The server requires conditional requests to prevent lost updates.", source: "RFC 6585" },
  { code: 429, name: "Too Many Requests", summary: "The client has sent too many requests in a given time (rate limiting).", detail: "Check the Retry-After header and back off before retrying.", source: "RFC 6585" },
  { code: 431, name: "Request Header Fields Too Large", summary: "The headers are too large — often because of oversized cookies.", source: "RFC 6585" },
  { code: 451, name: "Unavailable For Legal Reasons", summary: "Access is blocked for legal reasons, such as a court order.", source: "RFC 7725" },
  { code: 500, name: "Internal Server Error", summary: "The server hit an unexpected error.", detail: "A generic catch-all. The cause is in the server logs, not the request.", source: "RFC 9110" },
  { code: 501, name: "Not Implemented", summary: "The server doesn't support the functionality required.", source: "RFC 9110" },
  { code: 502, name: "Bad Gateway", summary: "A proxy or gateway got an invalid response from the upstream server.", detail: "Common when an app server has crashed behind a load balancer or reverse proxy.", source: "RFC 9110" },
  { code: 503, name: "Service Unavailable", summary: "The server is temporarily overloaded or down for maintenance.", detail: "May include a Retry-After header. Search engines treat it as temporary.", source: "RFC 9110" },
  { code: 504, name: "Gateway Timeout", summary: "A proxy or gateway didn't get a response from the upstream server in time.", source: "RFC 9110" },
  { code: 505, name: "HTTP Version Not Supported", summary: "The server doesn't support the HTTP version used.", source: "RFC 9110" },
  { code: 507, name: "Insufficient Storage", summary: "The server can't store what's needed to complete the request (WebDAV).", source: "RFC 4918" },
  { code: 508, name: "Loop Detected", summary: "The server found an infinite loop while processing (WebDAV).", source: "RFC 5842" },
  { code: 511, name: "Network Authentication Required", summary: "The client must authenticate to gain network access, e.g. a Wi-Fi captive portal.", source: "RFC 6585" },
];
